# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"detect_shapefile_encoding": "00_geoloader.ipynb",
         "read_file_shp": "00_geoloader.ipynb"}

modules = ["geoloader.py"]

doc_url = "https://DoryanKaced.github.io/OMP/"

git_url = "https://github.com/DoryanKaced/OMP/tree/main/"

def custom_doc_links(name): return None
